# mood_questions.py
import random

question_pool = {
    "emotions": [
        "How are you feeling right now?",
        "What word best describes your mood today?",
        "Have you felt mostly happy, sad, or something else this week?",
        "Did you feel worried or anxious today?",
        "Have you laughed or smiled recently?",
        "Have you felt angry or frustrated lately?",
        "Is there something making you feel upset?",
        "Have you felt calm and relaxed today?",
        "Have you felt excited about anything recently?",
        "Do you feel hopeful about the future?",
        "Have you felt down or low in the past few days?",
        "Are you feeling proud of yourself for something?",
        "Do you feel more irritable than usual?",
        "Did you feel jealous or envious of anyone recently?",
        "Have you felt grateful today?",
        "Do your feelings change throughout the day?",
        "Is there anything that's making you feel good or bad right now?",
        "Do you feel in control of your emotions?",
        "Have you felt emotionally numb lately?",
        "Do you feel like crying sometimes?",
        "Have you felt any joy or excitement this week?",
        "Do you often feel worried for no clear reason?",
        "Do you feel supported by people around you?",
        "How do you usually handle your feelings?",
        "Do you feel comfortable sharing your feelings with others?",
    ],
    "energy": [
        "Do you feel full of energy today or more tired?",
        "How well did you sleep last night?",
        "Did you feel tired after waking up?",
        "Do you need naps during the day?",
        "Have you exercised recently?",
        "Has your appetite changed lately?",
        "Do you feel physically restless or relaxed?",
        "Are you able to get things done, or do you feel too tired?",
        "Do you feel like moving around or staying still today?",
        "Do you have the energy to do things you like?",
        "Have you felt sleepy during the day?",
        "Do you wake up feeling refreshed?",
        "Do you feel your energy drops at certain times of day?",
        "Does your energy level affect your mood?",
        "Do you feel exhausted after doing small things?",
        "Do you feel like you want to stay in bed all day?",
        "Is it easy for you to get out of bed in the morning?",
        "Do you feel physically tense or relaxed?",
        "Do you feel more energetic after seeing friends?",
        "Are you satisfied with your current energy level?",
        "Do you get tired easily?",
        "Do you use caffeine or energy drinks to stay awake?",
        "Do you think your tiredness is due to stress?",
        "Do you feel more energetic at certain times of the day?",
        "Are you able to rest when you need to?",
    ],
    "social": [
        "Have you talked to friends or family recently?",
        "Do you feel connected to people around you?",
        "Are you spending more time alone or with others?",
        "Have you wanted to avoid social activities?",
        "Do you feel lonely or isolated?",
        "Are you happy with your social life right now?",
        "Do you feel supported by your friends or family?",
        "Do you have someone to talk to if you need help?",
        "Did you make any new friends recently?",
        "Do you feel comfortable in group situations?",
        "Have you argued with anyone lately?",
        "Do you feel understood by people close to you?",
        "Do you like meeting new people?",
        "Do you prefer being alone or with others?",
        "Do you feel left out in social situations?",
        "Have you enjoyed spending time with others recently?",
        "Do you feel close to your family?",
        "Do you feel comfortable sharing your feelings with someone?",
        "Do you feel pressure to fit in?",
        "Are your relationships going well?",
        "Do you trust the people you talk to?",
        "Do you find it easy to make conversation?",
        "Have you reconnected with any old friends?",
        "Do you feel judged by others?",
        "Do you feel like you belong somewhere?",
    ],
    "mental_health": [
        "Have you been worrying a lot lately?",
        "Do you often feel stressed?",
        "Do you find it hard to concentrate?",
        "Have you lost interest in things you used to enjoy?",
        "Do you feel hopeful or hopeless about the future?",
        "Do you feel overwhelmed by your thoughts?",
        "Have you felt nervous or on edge?",
        "Do you find it hard to relax your mind?",
        "Do you feel satisfied with your mental health?",
        "Do you feel motivated to do things?",
        "Have you been overthinking things?",
        "Do you have trouble making decisions?",
        "Do you feel mentally tired or drained?",
        "Do you feel like you can handle your problems?",
        "Do you have trouble letting go of negative thoughts?",
        "Have you felt anxious in new situations?",
        "Do you feel your mental health affects your daily life?",
        "Do you feel comfortable asking for help?",
        "Do you ever feel panicked or scared for no reason?",
        "Do you feel mentally sharp or foggy?",
        "Do you feel positive about yourself?",
        "How do you calm your mind when you're stressed?",
        "Do you worry about things you can't control?",
        "Do you often feel down for no reason?",
        "Do you try to focus on positive things each day?",
    ],
    "daily_function": [
        "Are you able to focus on your work or studies?",
        "Do you find it easy to get daily tasks done?",
        "Do you feel productive?",
        "Have you been procrastinating a lot?",
        "Have you missed any appointments recently?",
        "Do you feel organized or scattered?",
        "Do you have a daily routine?",
        "Are you able to finish what you start?",
        "Do you feel overwhelmed by your responsibilities?",
        "How do you prioritize your tasks?",
        "Do you feel your daily life is manageable?",
        "Do you keep a to-do list or planner?",
        "Do you have trouble keeping up with chores?",
        "Are you able to balance work and relaxation?",
        "Do you feel satisfied with what you accomplish each day?",
        "Do you get distracted easily?",
        "Do you find it hard to get started on projects?",
        "Do you adapt well to changes in your schedule?",
        "Have you been late to things recently?",
        "Do you feel in control of your day?",
        "Do you multitask often?",
        "Do you feel you have enough time for yourself?",
        "Are you meeting your own expectations?",
        "Do you feel like you are falling behind?",
        "Do you get help when you need it?",
    ],
    "self_reflection": [
        "What is one thing you are grateful for today?",
        "What is something you did well this week?",
        "What would you like to improve about yourself?",
        "Is there something you've been avoiding?",
        "What positive change could you make tomorrow?",
        "What is your biggest source of stress right now?",
        "What does self-care look like for you?",
        "What did you do just for yourself today?",
        "Is there something you can let go of?",
        "How do you comfort yourself when you feel down?",
        "What is a goal you want to achieve this month?",
        "How do you show yourself kindness?",
        "What thoughts are holding you back?",
        "What inspires you to keep going?",
        "What helps you feel calm?",
        "What are your top priorities right now?",
        "How do you celebrate your successes?",
        "When did you last feel truly at peace?",
        "What are you most looking forward to?",
        "How do you recharge after a tough day?",
        "What is something new you learned recently?",
        "How do you handle disappointment?",
        "What is a value that's important to you?",
        "How do you encourage yourself in difficult times?",
        "What habits help your well-being?",
    ],
    "coping": [
        "What helps you deal with stress?",
        "Do you have healthy ways to relax?",
        "How do you unwind after a tough day?",
        "Do you talk to someone when you're upset?",
        "What activities help you calm down?",
        "How do you distract yourself from worries?",
        "Do you have a favorite comfort food or activity?",
        "How do you take care of yourself during hard times?",
        "Do you go outside or exercise to feel better?",
        "How do you get support from others?",
        "Do you write or draw about your feelings?",
        "How do you reward yourself after a challenge?",
        "What makes you feel safe?",
        "Do you meditate or practice mindfulness?",
        "How do you manage frustration?",
        "What small thing brings you comfort?",
        "Do you try to focus on what you can control?",
        "How do you deal with setbacks or failures?",
        "Do you allow yourself to rest?",
        "How do you handle criticism or negative feedback?",
        "What do you do to boost your mood?",
        "How do you recover from a bad day?",
        "Do you set boundaries to protect your well-being?",
        "How do you ground yourself in the present moment?",
        "Do you have a support network you trust?",
    ],
}
def get_random_questions(num=10):
    selected = []
    categories = list(question_pool.keys())
    while len(selected) < num:
        cat = random.choice(categories)
        q = random.choice(question_pool[cat])
        if q not in selected:
            selected.append(q)
    return selected
